#!/bin/bash
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$GOBIN
cd /home/developer
echo "let g:pathogen_disabled = [$DISABLE]" >> .vimrc
echo "execute pathogen#infect('/ext/bundle/{}')" >> .vimrc
# mkdir -p /home/developer/.vim_runtime/temp_dirs
cat .vimrc~ >> .vimrc
echo "source /ext/.vimrc" >> .vimrc
cd /home/developer/workspace/
ctags -R --fields=+laimS --languages=php
#stty=-ixon
git config --global user.name "$GIT_USERNAME"
git config --global user.email "$GIT_EMAIL"
stty stop '' -ixoff ; vim $@
#vim $@
